name: Build & release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish to Docker Hub
        working-directory: proxy
        run: |
          docker build \
            --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --build-arg "BUILD_REVISION=$(git rev-parse --short "${GITHUB_SHA}")" \
            --tag "${DOCKER_IMAGE}" \
            .
          docker login --username "$( dirname $GITHUB_REPOSITORY )" --password-stdin <<< "${DOCKER_TOKEN}"
          docker push "${DOCKER_IMAGE}"
        env:
          DOCKER_IMAGE: privaterelay/privaterelay
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TAG: 'latest'
