name: Build & release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Buildscript
      run: .ci/scripts/build
