name: Build & release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        working-directory: proxy
        run: |
          docker build --tag "${DOCKER_SERVER}/${GITHUB_REPOSITORY}/${TAG}:latest" .
          docker login --username "$( dirname $GITHUB_REPOSITORY )" --password-stdin "${DOCKER_SERVER}" <<< "${DOCKER_TOKEN}"
          docker push "${DOCKER_SERVER}/${GITHUB_REPOSITORY}/${TAG}:latest"
        env:
          DOCKER_SERVER: docker.pkg.github.com
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'haproxy'
