name: Test
on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    name: tf fmt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      - name: Check *.tf
        run: |
          terraform fmt -check -recursive
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28
      - name: Build & run HAProxy
        working-directory: proxy
        run: |
          terraform init
          terraform apply -auto-approve
          docker build --tag private-relay .
          docker run --name private-relay --rm --detach --publish 8080:443 private-relay
      - name: Run cURL test for httpbin
        run: |
          curl -visSL \
          --fail \
          --connect-to httpbin.org:443:127.0.0.1:8080 \
          --header 'Host: httpbin.org' \
          https://httpbin.org/anything
      - name: Run cURL test for GitHub API
        run: |
          curl -visSL \
          --fail \
          --connect-to httpbin.org:443:127.0.0.1:8080 \
          --header 'Host: api.github.com' \
          https://api.github.com
      - name: Run tests
        working-directory: proxy/test/
        run: |
          yarn

          GITHUB_API_ENDPOINT='https://api.github.com' \
          GITHUB_API_ENDPOINT_RELAY="https://127.0.0.1:8080" \
          HTTPBIN_ENDPOINT="https://httpbin.org" \
          HTTPBIN_ENDPOINT_RELAY="https://127.0.0.1:8080" \
          yarn test
        env:
          CI: true
      - name: Stop Docker container
        working-directory: proxy
        run: |
          docker stop private-relay
